[package]
name = "bevy_camera_extras"
version = "0.1.4"
edition = "2021"
repository = "https://github.com/rydb/bevy_camera_extras"
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "A crate containing a collection of utilities to making working with cameras in bevy easier."

[dependencies]
bevy = { version = "0.11", default-features = false, features = ["bevy_render", "bevy_core_pipeline", "bevy_asset"]}
glam = "0.24"
bevy_component_extras = "0.1"

[dev-dependencies]
bevy = { version = "0.11", features = ["dynamic_linking"]}
bevy-inspector-egui = "0.19"
